#!/bin/bash

function logo {
  bash <(curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo)
}

function line {
  echo "-----------------------------------------------------------------------------"
}

function main_tools {
  bash <(curl -s https://raw.githubusercontent.com/cpiteam/MUON/main/main_tools)
}

function docker {
  bash <(curl -s https://raw.githubusercontent.com/cpiteam/MUON/main/docker)
}

function setup_compose {
  curl -o docker-compose.yml https://raw.githubusercontent.com/muon-protocol/muon-node-js/testnet/docker-compose-pull.yml
}

function docker_start {
  docker-compose up -d
}


function txt {
bash <(curl -s https://raw.githubusercontent.com/cpiteam/logo/main/Logo%20last)
}

colors
line
sleep 1 && logo && sleep 3 
line
echo "Installing tools and docker"
line
main_tools
docker
line
echo "Setup compose"
line
setup_compose
line
echo "Start"
docker_start
sleep 1 && txt && sleep 2 
line


